title: SiG FSTM
description: We are SiG FSTM a small community from KUIS. This website will be the place where we share all of our activities!
permalink: /posts/:title/
excerpt_separator: <!--more-->

#post pagination
paginate_path: "/page:num/"
paginate: 5

# Disqus Comments :)
disqus:
  shortname: sig-fstm
